### ISSUE TITLE
Heroku Deploy failing

### ISSUE THREAD

**Issue by ravxl** [thermondo/threesixty#559]
Hi, I've tried to deploy to heroku by clicking on deploy to heroku button and I'm getting this error below:

-----> Building on the Heroku-20 stack
-----> Using buildpack: heroku/python
-----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/python.tgz
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed

**Comment by syphar** [comment]
thank you for the report! 

We migrated the tool to another package manager, and forgot to update the `app.json`. I just added, now everything should be fine when you try creating the app  again: 

9278bd2b78b7c10c17f76cb79b3ce5b9a475c316
